<?php
use Album\Form\AlbumDataForm;
use Album\Model\Entity\AlbumEntity;

/** @var AlbumEntity $album */
$album = $this->albumEntity;

/** @var AlbumDataForm $form */
$form = $this->albumForm;
$form->setAttribute(
    'action', $this->url('album-update-handle', ['id' => $album->getId()])
);

$this->headTitle('Edit album');
?>

<div class="jumbotron">
    <h1>Edit album</h1>
</div>

<div class="alert alert-danger">
    <strong><?= $this->message; ?></strong>
</div>

<div class="well">
    <?= $this->form()->openTag($form); ?>
    <div class="form-group">
        <?= $this->formLabel($form->get('artist')); ?>
        <div class="col-sm-10">
            <?= $this->formElement($form->get('artist')); ?>
            <?= $this->formElementErrors($form->get('artist')); ?>
        </div>
    </div>
    <div class="form-group">
        <?= $this->formLabel($form->get('title')); ?>
        <div class="col-sm-10">
            <?= $this->formElement($form->get('title')); ?>
            <?= $this->formElementErrors($form->get('title')); ?>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?= $this->formElement($form->get('save_album')); ?>
        </div>
    </div>
    <?= $this->form()->closeTag(); ?>
</div>

<p>
    <a href="<?= $this->url('album') ?>" class="btn btn-success">
        Back to album list
    </a>
</p>
